import { classifyText } from "./symptoms";
import type { RedFlag } from "./red-flags";
import type { TriageResult } from "./triage-scorer";
import type { InterviewAnswer } from "./socrates";

export type StructuredHistory = {
  chiefComplaint: string;
  hpi: string;
  pastHistory: string;
  medications: string[];
  allergies: string[];
  reviewOfSystems: string;
  suggestedDepartment: string;
  classification: { cluster: string; confidence: number };
};

const MED_PATTERNS = /\b(paracetamol|metformin|amlodipine|aspirin|insulin|azithromycin|ors)\b/gi;
const ALLERGY_PATTERNS = /\b(allergic to|allergy to)\s+([a-z]+)/gi;

export function extractEntities(text: string) {
  const meds = Array.from(text.matchAll(MED_PATTERNS), (m) => m[0]);
  const allergies: string[] = [];
  for (const m of Array.from(text.matchAll(ALLERGY_PATTERNS))) {
    allergies.push(m[2]);
  }
  return { medications: Array.from(new Set(meds.map((m) => m.toLowerCase()))), allergies };
}

export function buildStructuredHistory(
  complaint: string,
  answers: InterviewAnswer[],
  freeText?: string
): StructuredHistory {
  const narrative = [
    complaint,
    ...answers.map((a) => `${a.question} ${a.answer}`),
    freeText ?? "",
  ].join(". ");

  const classification = classifyText(narrative);
  const { medications, allergies } = extractEntities(narrative);

  const hpiLines = answers.map((a) => `• ${a.question.replace("?", "")}: ${a.answer}`);
  if (freeText?.trim()) hpiLines.push(`• Patient narrative: ${freeText.trim()}`);

  return {
    chiefComplaint: complaint,
    hpi: hpiLines.join("\n"),
    pastHistory: "Not reported during kiosk intake (verify with patient).",
    medications: medications.length ? medications : ["None reported"],
    allergies: allergies.length ? allergies : ["NKDA reported"],
    reviewOfSystems: `Positive findings cluster: ${classification.cluster}. Confidence ${(classification.confidence * 100).toFixed(0)}%.`,
    suggestedDepartment: classification.department,
    classification: { cluster: classification.cluster, confidence: classification.confidence },
  };
}

export function physicianSummary(
  history: StructuredHistory,
  triage: TriageResult,
  redFlags: RedFlag[],
  patientName: string
): string {
  const flagBlock = redFlags.length
    ? redFlags.map((f) => `⚠ ${f.label} — ${f.action}`).join("\n")
    : "No emergency red flags detected.";

  return [
    `CLINICAL INTAKE SUMMARY — ${patientName}`,
    `Generated by MediKiosk ML pipeline`,
    "",
    `TRIAGE: ${triage.level.toUpperCase()} (score ${triage.score}/100, P=${triage.probability})`,
    `Model: ${triage.model}`,
    "",
    "RED FLAGS:",
    flagBlock,
    "",
    `CHIEF COMPLAINT: ${history.chiefComplaint}`,
    "",
    "HPI:",
    history.hpi,
    "",
    `PAST HISTORY: ${history.pastHistory}`,
    `MEDICATIONS: ${history.medications.join(", ")}`,
    `ALLERGIES: ${history.allergies.join(", ")}`,
    `ROS: ${history.reviewOfSystems}`,
    "",
    `Suggested routing: ${history.suggestedDepartment}`,
    `ML symptom cluster: ${history.classification.cluster} (${(history.classification.confidence * 100).toFixed(0)}% confidence)`,
  ].join("\n");
}
